version: '3.8'

services:
  planner:
    build:
      context: ./planner
    ports:
      - "3000:3000"
    networks:
      - my_network

  worker:
    build:
      context: ./worker
    networks:
      - my_network
    depends_on:
      - planner
    environment:
      - ADD=true
      - MULT=true
    scale: 10

networks:
  my_network:
    driver: bridge
