version: '3.7'

services:
  planner:
    build:
      context: ./planner
    ports:
      - "3000:3000"
    networks:
      - my_network

  worker:
    build:
      context: ./worker
    networks:
      - my_network
    environment:
      - ADD=true
      - MULT=true
      - ADDRESSHOST=worker
    scale: 10

  worker-add:
    build:
      context: ./worker
    networks:
      - my_network
    environment:
      - ADD=true
      - MULT=false
      - ADDRESSHOST=worker-add
    scale: 10

  worker-mult:
    build:
      context: ./worker
    networks:
      - my_network
    environment:
      - ADD=false
      - MULT=true
      - ADDRESSHOST=worker-mult
    scale: 10

networks:
  my_network:
    driver: bridge
