version: '3.7'

services:
  planner:
    build:
      context: ./planner
    ports:
      - "3000:3000"
    networks:
      - my_network

  worker:
    build:
      context: ./worker
    networks:
      - my_network
          
    ports:
      - "8080:8080"
    environment:
      - ADD=false
      - MULT=true
  
  worker2:
    build:
      context: ./worker
    networks:
      - my_network    
    ports:
      - "8070:8070"
    environment:
      - ADD=true
      - MULT=false
  


  # worker_add_only:
  #   build:
  #     context: ./worker
  #   networks:
  #     - my_network
  #   environment:
  #     - ADD=true
  #     - MULT=false
  #   deploy:
  #     replicas: 10

  # worker_mult_only:
  #   build:
  #     context: ./worker
  #   networks:
  #     - my_network
  #   environment:
  #     - ADD=false
  #     - MULT=true
  #   deploy:
  #     replicas: 10

networks:
  my_network:
    driver: bridge
